###

GET http://localhost:9000/employees


###

GET http://localhost:9000/employees/1


###
## Create a 
POST http://localhost:9000/employees
content-type: application/json

{
    "name": "",
    "phonenumber": "0945456667",
    "email": "",
    "address": "23aaaaaaaaaaaaaaaaaaaaaa",
    "gender": "Male",
    "position": "Admin",
    "birthday": "1999-07-17"
}

###
