###

GET http://localhost:9000/members

content-type: application/json


###
## Create a 
POST http://localhost:9000/members
content-type: application/json

{
    "name": "Sĩ Nguyên",
    "email": "singuyen@gmail.com",
    "address": "76 Lý Thái Tông.....",
    "gender": "Male",
    "contact": "0335954321",
    "password": "singuyen@"
}

###